name: nexus
description: "Yet another Matrix client"
version: 1.0.0
publish_to: none

flutter:
  uses-material-design: true

environment:
  sdk: "^3.9.2"

dependency_overrides:
  analyzer: ^8.4.0
  source_gen: ^4.0.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_riverpod: ^3.0.3
  hooks_riverpod: ^3.0.3
  intl: ^0.20.1
  app_links: ^6.1.1
  fast_immutable_collections: ^11.0.0
  path_provider: ^2.1.3
  permission_handler: ^12.0.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  freezed_annotation: ^3.1.0
  image_picker: ^1.1.2
  file_picker: ^10.3.3
  path: ^1.9.0
  dynamic_system_colors: ^1.8.0
  collection: ^1.19.1
  window_manager: ^0.5.1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.8.0
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  json_serializable: ^6.8.0
  riverpod_lint: ^3.0.3
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  ios: true
  android: true
  image_path: assets/icon.png
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: assets/foreground.png
  remove_alpha_ios: true