name: nexus
description: "Yet another Matrix client"
version: 1.0.0
publish_to: none

flutter:
  assets:
    - assets/
  uses-material-design: true

environment:
  sdk: "^3.9.2"

dependency_overrides:
  vodozemac:
    git:
      url: https://github.com/famedly/dart-vodozemac
      ref: krille/use-specced-olm-session-config
      path: dart
  analyzer: ^8.4.0
  source_gen: ^4.0.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_riverpod: ^3.0.3
  hooks_riverpod: ^3.0.3
  intl: ^0.20.1
  fast_immutable_collections: ^11.0.0
  path_provider: ^2.1.3
  url_launcher: ^6.2.6
  freezed_annotation: ^3.1.0
  image_picker: ^1.1.2
  file_picker: ^10.3.3
  path: ^1.9.0
  dynamic_system_colors: ^1.8.0
  collection: ^1.19.1
  window_manager: ^0.5.1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
  flutter_chat_core: ^2.0.0
  flyer_chat_image_message: ^2.2.2
  flyer_chat_system_message: ^2.1.13
  flyer_chat_file_message: ^2.3.1
  flyer_chat_text_message:
    git:
      url: https://github.com/Henry-Hiles/flutter_chat_ui
      path: packages/flyer_chat_text_message
  flutter_chat_ui:
    git:
      url: https://github.com/Henry-Hiles/flutter_chat_ui
      path: packages/flutter_chat_ui
  flutter_link_previewer:
    git:
      url: https://github.com/Henry-Hiles/flutter_chat_ui
      path: packages/flutter_link_previewer
  matrix: ^4.1.0
  sqflite_common_ffi: ^2.3.6
  color_hash: ^1.0.1
  flutter_vodozemac: ^0.4.1
  flutter_widget_from_html_core: ^0.17.0
  flutter_svg: ^2.2.2
  simple_secure_storage: ^0.3.6
  json_annotation: ^4.9.0
  vodozemac: ^0.4.0
  clipboard: ^3.0.10
  shared_preferences: ^2.5.3
  mention_tag_text_field: ^0.0.9
  fluttertagger: ^2.3.1
  
dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.8.0
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  riverpod_lint: ^3.0.3
  flutter_launcher_icons: ^0.14.1
  json_serializable: ^6.11.1

flutter_launcher_icons:
  ios: true
  android: true
  image_path: assets/icon.png
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: assets/foreground.png
  remove_alpha_ios: true